config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :galaxies
  root  'galaxies#landing'
  patch '/galaxies/:id(.:format)'  => 'galaxies#update', :as => 'update_galaxy'
  post '/galaxies/find/' => 'galaxies#find'
  post '/galaxies/findadvanced' => 'galaxies#findadvanced'
  get '/galaxies/:id/delete' => 'galaxies#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
     has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumbnail: "150x150#"}
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
     validates_presence_of :image, :message => " must be attached."
     validates_presence_of :galaxy_type, :message => " can't be empty."
     validates_presence_of :name, :message => " can't be empty."
     validates_presence_of :mass, :message => " can't be empty."
     validates_presence_of :distance, :message => " can't be empty."
     validates_presence_of :num_stars, :message => " can't be empty."
     validates_presence_of :diameter, :message => " can't be empty."
     validates_presence_of :notable_features, :message => " were either not saved or are empty."
     validates :mass, :numericality => { greater_than: 0 }
     validates :distance, :numericality => { greater_than: 0 }
     validates :num_stars, :numericality => { greater_than: 0 }
     validates :diameter, :numericality => { greater_than: 0 }
     validates_uniqueness_of :name, :message => " already in database."
     
     belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :galaxy
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
    
   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
  end

  protect_from_forgery with: :exception
end

app/controllers/galaxies_controller.rb
class GalaxiesController < ApplicationController
  
  before_action :set_galaxy, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy] 
  
  # GET /galaxies
  # GET /galaxies.json
  def index
      @galaxies = Galaxy.all
      @signed_in = user_signed_in? 
      if @galaxies.count == 0
        flash[:zeroCount] = "No galaxies yet. Change that by clicking "
      end
    else
  end

  # GET /galaxies/1
  # GET /galaxies/1.json
  def show
   @signed_in = user_signed_in?
   @authorized = current_user == Galaxy.find(params[:id]).user
   @user = User.where("id = #{@galaxy.user_id}")
   puts "Username is: "+@user.pluck(:email).join("").to_s
  end
  
  # GET /galaxies/find
  def find
   @name = Galaxy.where("name = '#{params[:name].split(" ").map{|n| n.capitalize}.join(" ")}'")
   puts @name
    if !@name.blank?
      redirect_to '/galaxies/'+@name.pluck(:id).join("")
    else
      flash[:not_found] = "Record not found."
      redirect_to galaxies_url
    end
  end
  # GET /galaxies/new
  def new
    if current_user
    @galaxy = current_user.galaxy.build
  else
    redirect_to '/users/sign_in'
  end
  end
  
  # GET /galaxies/findadvanced
  def findadvanced
    @signed_in = user_signed_in?
    @record = Galaxy.where("galaxy_type = '#{params[:type]}' and mass between #{params[:lower_mass]} and #{params[:upper_mass]} and distance between #{params[:lower_distance]} and #{params[:upper_distance]} 
    and diameter between #{params[:lower_diameter]} and #{params[:upper_diameter]} and num_stars between #{params[:lower_stars]} and #{params[:upper_stars]}")
    @signed_in = user_signed_in?
  end

  # GET /galaxies/1/edit
  def edit
    
    @signed_in = user_signed_in?
    
    @galaxy = Galaxy.find(params[:id])
  end

  # POST /galaxies
  # POST /galaxies.json
  def create
    @galaxy = current_user.galaxy.build(galaxy_params)
    respond_to do |format|
      if @galaxy.save
        format.html { redirect_to @galaxy }
        format.json { render :show, status: :created, location: @galaxy }
        flash[:notice] = "Galaxy successfully created."
      else
        format.html { render :new }
        format.json { render json: @galaxy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galaxies/1
  # PATCH/PUT /galaxies/1.json
  def update
    respond_to do |format|
      if @galaxy.update(galaxy_params)
        format.html { redirect_to @galaxy }
        format.json { render :show, status: :ok, location: @galaxy }
        flash[:notice] = "Galaxy successfully updated."
      else
        format.html { render :edit }
        format.json { render json: @galaxy.errors, status: :unprocessable_entity }
      end
    end
  end
  


  # DELETE /galaxies/1
  # DELETE /galaxies/1.json
  def destroy
    Galaxy.delete(@galaxy)
    respond_to do |format|
      format.html { redirect_to galaxies_url}
      format.json { head :no_content }
      flash[:notice] = "Galaxy successfully deleted."
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galaxy
      @galaxy = Galaxy.find(params[:id])
    end
    
    def set_record
       @record = Galaxy.where("mass between #{params[:lower_mass]} and #{params[:upper_mass]} and distance between #{params[:lower_distance]} and #{params[:upper_distance]} 
    and diameter between #{params[:lower_diameter]} and #{params[:upper_diameter]} and num_stars between #{params[:lower_stars]} and #{params[:upper_stars]}")
      redirect_to '/galaxies'
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def galaxy_params
      params.require(:galaxy).permit(:name, :galaxy_type, :distance, :num_stars, :diameter, :mass, :notable_features, :image)
    end
    
    def user_params
      params.require(:user).permit(:email,:username,:password)
    end
    
    def correct_user
     @user= User.find(current_user.id)
     redirect_to(root_url) unless current_user.id == @galaxy.user.id
    end
    
    def landing
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galaxies_helper.rb
module GalaxiesHelper
end

app/views/galaxies/_form.html.erb
<%= form_for @galaxy, url: galaxies_path, :html => { multipart: true } do |form| %>
  <% if @galaxy.errors.any? %>

      <h2><%= pluralize(galaxy.errors.count, "error") %> prohibited this galaxy from being saved:</h2>
     
      <% galaxy.errors.full_messages.each do |message| %>
        <div class="card error" >
          <div class="section">
             <%= message %>
          </div>
         </div>

        
      <% end %>
     
  <% end %>
<fieldset>
  <legend style="text-align:center;font-size:24px;">Add a Galaxy</legend>
   <div class="input-group fluid">
     <%= form.label :name %>
    <%= form.text_field :name, id: :galaxy_name %>
   </div>
    
  <div class="input-group fluid">
    <%= form.label :galaxy_type %>
     <%= form.select :galaxy_type, options_for_select(["Spiral","Elliptical","Irregular"]), :selected => 'Spiral' %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_distance">Distance (in kilo-lightyears)</label>
    <%= form.text_field :distance, id: :galaxy_distance %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_num_stars">Number of stars (in billions)</label>
    <%= form.number_field :num_stars, id: :galaxy_num_stars %>
  </div>
  
  
  <div class="input-group fluid">
    <label for="galaxy_diameter">Diameter (in lightyears)</label>
    <%= form.text_field :diameter, id: :galaxy_diameter %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_mass">Mass (in solar masses)</label>
    <%= form.text_field :mass, id: :galaxy_mass %>
  </div>

  <div class="input-group fluid">
    <%= form.text_area :notable_features, id: :galaxy_notable_features, style:"display:none;visibility:hidden;", rows:"11", cols:"100" %>
  </div>
  
  
  <div style="text-align:center" id="addfeatures">
    <span id="addfeature" class="button" style='cursor:pointer'>Add Notable Features +</span>
    <span id="savefeature" class="button">Save All Features</span>
  </div>
  
  <div class="input-group fluid">
  <%= form.label :image,'Upload image', class: 'button', id: 'filelabel', style:"margin-left:13%;" %>
  <%= form.file_field :image %>
  <span id="img-text">
    <img height="150px" width="150px" id="img-preview">
    </span>
    <div class="input-group fluid">
    <button id="remove" style="visibility:hidden;display:none;" class="secondary">Remove Image</button>
  </div>
  </div>
  
    <div style="text-align:center">
   <input type="button" class="tertiary" value="Back" onclick="location.href='/galaxies'">

     <input id="submitform" type="submit" class="primary" value="Submit Galaxy">

    
  </div>
  
</fieldset>
  
  
<% end %>
<script>
$('#savefeature').hide();

 var hidden = $('#galaxy_notable_features').val();
 var valString = "";
  
 var values = {};
 var newFeatureCount = 0;
 
 $('#addfeature').click(()=>{
    $('#savefeature').show();
  newFeatureCount++;
  
   $('#addfeatures').append(`<span id='feature-span${newFeatureCount}'><br><input id="newfeature${newFeatureCount}" type='text' style='width:34%'> <span id='remove${newFeatureCount}' class='button'>Remove</span><span id="saved${newFeatureCount}"></span></span>`);
   
   $('#savefeature').click(()=>{
   
    for(var i=0;i<$('#addfeatures input').length;i++){
        values[i] = $('#addfeatures input')[i].value;
    }
     
    console.log(values);
     resetValues();
     sweetAlert("All notable features saved!");
     
   });
   
  $('#remove'+newFeatureCount).click(()=>{
      
   $('#feature-span'+newFeatureCount).remove();
   
   delete values[newFeatureCount-1];

   
   resetValues();
   
   console.log(values);
   
   newFeatureCount--;
   if(newFeatureCount==0)
   $('#savefeature').hide();
 });
 
 });
 
 $('#submitform').click((e)=>{
    e.preventDefault();
    sweetAlert('Did you enter all required fields and save the notable features you entered?').then(()=>{$('#new_galaxy').submit();});
 });
 
function resetValues(){
  valString = "";
  $('#galaxy_notable_features').val("");
  for(var val of Object.values(values)){
       valString+=val+"\n";
     }
     console.log(hidden);
     $('#galaxy_notable_features').val(valString);
     
}
 
</script>

app/views/galaxies/edit.html.erb
<header>
<a href="/galaxies/new" class="button">Add</a>
<a href="/galaxies" class="button">Show Galaxies</a>


<div class="right">
  <input type="search" placeholder="Search">
<%= link_to 'Delete', @galaxy, method: :delete, data: { confirm: 'Are you sure?' }, class:'button' %>   
<%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'button' %>

</div>

</header>
<div class="container" id="galaxyform">

    <div class="row">
        <div id="form" class="col-lg-8 col-lg-offset-2 col-md-12 col-sm-14">
            
<%= form_for @galaxy, url: update_galaxy_url, :html => { multipart: true } do |form| %>
  <% if @galaxy.errors.any? %>

        <h2><%= pluralize(galaxy.errors.count, "error") %> prohibited this galaxy from being saved:</h2>
     
      <% galaxy.errors.full_messages.each do |message| %>
        <div class="card error">
          <div class="section">
             <%= message %>
          </div>
         </div>
      <% end %>
     
  <% end %>
<fieldset>
  <legend style="text-align:center;font-size:24px;">Edit '<%=@galaxy.name.capitalize%>' Galaxy</legend>
   <div class="input-group fluid">
     <%= form.label :name %>
    <%= form.text_field :name, id: :galaxy_name %>
   </div>
    
  <div class="input-group fluid">
    <%= form.label :galaxy_type %>
     <%= form.select :galaxy_type, options_for_select(["Spiral","Elliptical","Irregular"]), :selected => 'Spiral' %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_distance">Distance (in kilo-lightyears)</label>
    <%= form.text_field :distance, id: :galaxy_distance %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_num_stars">Number of stars (in billions)</label>
    <%= form.number_field :num_stars, id: :galaxy_num_stars %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_diameter">Diameter (in lightyears)</label>
    <%= form.text_field :diameter, id: :galaxy_diameter %>
  </div>

  <div class="input-group fluid">
    <label for="galaxy_mass">Mass (in solar masses)</label>
    <%= form.text_field :mass, id: :galaxy_mass %>
  </div>

  <div class="input-group fluid">
    <%= form.text_area :notable_features, id: :galaxy_notable_features, placeholder: 'Enter notable features separated by a spaces.' %>
  </div>
  
  <div class="input-group fluid">
  <%= form.label :image,'Upload image', class: 'button', id: 'filelabel' %>
  <%= form.file_field :image %>
  <span id="img-text">
    <img height="150px" width="150px" id="img-preview">
    </span>
    <div class="input-group fluid">
    <button id="remove" style="visibility:hidden;display:none;" class="secondary">Remove Image</button>
  </div>
  </div>
  
    <div style="text-align:center">
   <input type="button" class="tertiary" value="Back" onclick="location.href='/galaxies'">

     <input type="submit" class="primary" value="Submit Galaxy">

    
  </div>
  
</fieldset>
  
  
<% end %>

        </div>
         
</div>
</div>

<script>
$(document).ready(()=>{
   
const backgrounds = ["https://images3.alphacoders.com/169/thumb-1920-169667.jpg",
"https://images.alphacoders.com/805/thumb-1920-805180.jpg",
"https://images6.alphacoders.com/550/thumb-1920-550127.jpg"];
     
$('#galaxyform').parent().css('background-image',"url("+backgrounds[Math.floor(Math.random() * 3)]+")");

$('#galaxyform').css('opacity',0.8);
$('#galaxyform .row').children().children().css('background-color','#C1CEF6');

$('input:file').on('change',()=>{
    $('#img-preview').css('visibility','visible');
       $('#img-preview').css('display','unset');
   var reader = new FileReader();
        reader.onload = function(e) {
            try{
                $('#img-preview').attr('src', e.target.result);
            }catch(e){
                $('#img-text').text("Error. Image preview couldn't be loaded.");
            }
            
        }
        reader.readAsDataURL($('input:file')[0].files[0]);
        
    $('#remove').css('display','unset');
    $('#remove').css('visibility','visible');
    
    $('#remove').click((e)=>{
        e.preventDefault();
      $('#img-preview').attr('src',""); 
      $('#img-preview').css('visibility','hidden');
      $('#img-preview').css('display','none');
        $('#remove').css('display','none');
    $('#remove').css('visibility','hidden');

    });
});



});

</script>

app/views/galaxies/findadvanced.html.erb
<header>
  
  <a href="/galaxies/new" class="button">Add</a>
  <a href="/galaxies" class="button">Show Galaxies</a>
  <div class="right">
    <form action="/galaxies/find/" method="post" style="display:inline-block;margin:0px;padding:0px;background:none;border:none;">
      <input name="name" placeholder='Enter Name To Search' style="">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>
    <button id="search-button">Advanced Search</button>
    <% if !@signed_in %>
      <a href="/users/sign_in" class="button">Login</a>
  <a href="/users/sign_up" class="button">Register</a>
  <% else %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'button' %>
  <% end %>
  </div>
 
</header>

<div style="text-align:center;margin-top:4%;">
    <p id="notice"><%= notice %></p>
</div>

<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
			<iframe id="ytplayer" frameborder="0" src="https://www.youtube.com/embed/5gQ5CMcX_pA?autoplay=1&loop=1&rel=0" allowfullscreen></iframe>
		</div>
		<% if @record.count == 0 %>
    <div class="centered" style="background-color:gray;opacity:.75;margin:0 auto;">
      <h2><%= flash[:zeroCount] %><%= link_to 'here','/galaxies/new' %>.</h2>
    </div>
    <% elsif flash[:not_found] %>
    <div class="centered" style="background-color:gray;opacity:.75;margin:0 auto;">
         <h2><%= flash[:not_found] %></h2>   
    </div>
   <% else %>
  <div class="container" id="index">
    <div class="row">
      <% @record.each do |galaxy| %>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="card shadowed">
        <%= link_to image_tag(galaxy.image.url(:medium)), galaxy %>
        <div class="section double-padded">
         <strong><h1><%= galaxy.name.capitalize %></h1> </strong>
          </div>
      </div>
        
    </div>
        
    <% end %>
     <% end %>
    </div>
    
  </div>
    
<br>
<script>
$(document).ready(()=>{
     $('#search-button').click(()=>{
   sweetAlert({html:`<%= form_tag "/galaxies/findadvanced", :id => 'advanced-search' do %>
     <div class='input-group-field'>
     <strong><%= label_tag 'Type' %></strong>
     <span><%= select_tag :type, options_for_select(["Spiral","Elliptical","Irregular"]), :selected => 'Spiral' %></span>
     </div>
     <div class='input-group-field'>
     <strong><%= label_tag 'Mass' %></strong>
     <span>Between <%= text_field_tag :lower_mass, 0 %> and <%= text_field_tag :upper_mass,  Galaxy.maximum(:mass) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Distance' %></strong>
     <span>Between <%= text_field_tag :lower_distance,  0%> and <%= text_field_tag :upper_distance,  Galaxy.maximum(:distance) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Diameter' %></strong>
     <span>Between <%= text_field_tag :lower_diameter,  0%> and <%= text_field_tag :upper_diameter,  Galaxy.maximum(:diameter) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Number of Stars' %></strong>
     <span>Between <%= text_field_tag :lower_stars,  0%> and <%= text_field_tag :upper_stars,  Galaxy.maximum(:num_stars) %></span>
     </div>
     <br>
    <%= submit_tag "Search" %>
 <% end %><br>`,width:'50%',showConfirmButton:false, showCloseButton:true, confirmButtonText:'Search'})
});

  });
</script>

app/views/galaxies/index.html.erb
<header>
  <% if @signed_in %>
  <a href="/galaxies/new" class="button">Add</a>
  <% end %>
  <a href="/galaxies" class="button">Show Galaxies</a>
  <div class="right">
    <form action="/galaxies/find/" method="post" style="display:inline-block;margin:0px;padding:0px;background:none;border:none;">
      <input name="name" placeholder='Enter Name To Search' style="">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>
    <button id="search-button">Advanced Search</button>
    <% if !@signed_in %>
     <a href="/users/sign_in" class="button">Login</a>
  <a href="/users/sign_up" class="button">Register</a>
  <% else %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'button' %>
    <% end %>
  </div>
 
</header>

<div style="text-align:center;margin-top:4%;">
    <p id="notice"><%= notice %></p>
</div>

<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
			<iframe id="ytplayer" frameborder="0" src="https://www.youtube.com/embed/5gQ5CMcX_pA?autoplay=1&loop=1&rel=0" allowfullscreen></iframe>
		</div>
		<% if @galaxies.count == 0 %>
    <div class="centered" style="background-color:gray;opacity:.75;margin:0 auto;">
      <h2><%= flash[:zeroCount] %><strong><%= link_to 'here','/galaxies/new' %>.</strong></h2>
    </div>
    <% elsif flash[:not_found] %>
    <div class="centered" style="background-color:gray;opacity:.75;margin:0 auto;">
         <h2><%= flash[:not_found] %></h2>   
    </div>
   <% else %>
  <div class="container" id="index">
    <div class="row">
      <% @galaxies.each do |galaxy| %>
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="card shadowed">
        <%= link_to image_tag(galaxy.image.url(:medium)), galaxy, :style=> "opacity:1;" %>
        <div class="section double-padded">
         <strong><h1><%= galaxy.name.split(" ").map{|n| n.capitalize}.join(" ") %></h1> </strong>
          </div>
      </div>
        
    </div>
        
    <% end %>
     <% end %>
    </div>
    
  </div>
    
<br>
<script>
$(document).ready(()=>{
     $('#search-button').click(()=>{
   sweetAlert({html:`<%= form_tag "/galaxies/findadvanced", :id => 'advanced-search' do %>
     <div class='input-group-field'>
     <strong><%= label_tag 'Type' %></strong>
     <span><%= select_tag :type, options_for_select(["Spiral","Elliptical","Irregular"]), :selected => 'Spiral' %></span>
     </div>
     <div class='input-group-field'>
     <strong><%= label_tag 'Mass' %></strong>
     <span>Between <%= text_field_tag :lower_mass, 0 %> and <%= text_field_tag :upper_mass,  Galaxy.maximum(:mass) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Distance' %></strong>
     <span>Between <%= text_field_tag :lower_distance,  0%> and <%= text_field_tag :upper_distance,  Galaxy.maximum(:distance) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Diameter' %></strong>
     <span>Between <%= text_field_tag :lower_diameter,  0%> and <%= text_field_tag :upper_diameter,  Galaxy.maximum(:diameter) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Number of Stars' %></strong>
     <span>Between <%= text_field_tag :lower_stars,  0%> and <%= text_field_tag :upper_stars,  Galaxy.maximum(:num_stars) %></span>
     </div>
     <br>
    <%= submit_tag "Search" %>
 <% end %><br>`,width:'50%',showConfirmButton:false, showCloseButton:true, confirmButtonText:'Search'})
});


});

</script>

app/views/galaxies/landing.html.erb
<html>
	<head>
	    <title>Galaxy Explorer</title>
      <style>
body {
	margin:0;
	padding:0;
	text-align:center;
	position:absolute;
}

#main{
    opacity:.5;
}

      </style>
	</head>
	<body>
		<div style="position: fixed; z-index: -99; width: 100%; height: 100%">
			<iframe src="https://player.vimeo.com/video/45563598?autoplay=1&controls=0&loop=1&rel=0&showinfo=0&autohide=1&wmode=transparent&hd=1&rel=0"  frameborder="0" allowfullscreen></iframe>
		</div>
		<div id="main" class="centered">
			<h2>
				<%= link_to 'Begin Your Journey','galaxies#index', class:'button primary' %>
			</h2>
		</div>
	</body>
</html>

app/views/galaxies/new.html.erb
<header>
<a href="/galaxies" class="button">Show Galaxies</a>

<div class="right">
  <form action="/galaxies/find/" method="post" style="display:inline-block;margin:0px;padding:0px;background:none;border:none;">
      <input name="name" placeholder='Enter Name To Search' style="">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <button><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>

 <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'button' %>
</div>

</header>
<div class="container" id="galaxyform">

    <div class="row">
        <div id="form" class="col-lg-8 col-lg-offset-2 col-md-12 col-sm-14">
            <%= render 'form', galaxy: @galaxy %>
        </div>
         
</div>
</div>

<script>
$(document).ready(()=>{
    
    $('#search-button').click(()=>{
   sweetAlert({html:`<%= form_tag "/galaxies/findadvanced", :id => 'advanced-search' do %>
     <div class='input-group-field'>
     <strong><%= label_tag 'Mass' %></strong>
     <span>Between <%= text_field_tag :lower_mass, 0 %> and <%= text_field_tag :upper_mass,  Galaxy.maximum(:mass) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Distance' %></strong>
     <span>Between <%= text_field_tag :lower_distance,  0%> and <%= text_field_tag :upper_distance,  Galaxy.maximum(:distance) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Diameter' %></strong>
     <span>Between <%= text_field_tag :lower_diameter,  0%> and <%= text_field_tag :upper_diameter,  Galaxy.maximum(:diameter) %></span>
     </div><hr>
     <div class='input-group-field'>
     <strong><%= label_tag 'Number of Stars' %></strong>
     <span>Between <%= text_field_tag :lower_stars,  0%> and <%= text_field_tag :upper_stars,  Galaxy.maximum(:num_stars) %></span>
     </div>
     <br>
    <%= submit_tag "Search" %>
 <% end %><br>`,width:'50%',showConfirmButton:false, showCloseButton:true, confirmButtonText:'Search'})
});
   
const backgrounds = ["https://images3.alphacoders.com/169/thumb-1920-169667.jpg",
"https://images.alphacoders.com/805/thumb-1920-805180.jpg",
"https://images6.alphacoders.com/550/thumb-1920-550127.jpg"];
     
$('#galaxyform').parent().css('background-image',"url("+backgrounds[Math.floor(Math.random() * 3)]+")");

$('#galaxyform').css('opacity',0.8);
$('#galaxyform .row').children().children().css('background-color','#C1CEF6');

$('input:file').on('change',()=>{
    $('#img-preview').css('visibility','visible');
    $('#img-preview').css('display','unset');
   var reader = new FileReader();
        reader.onload = function(e) {
            try{
                $('#img-preview').attr('src', e.target.result);
            }catch(e){
                $('#img-text').text("Error. Image preview couldn't be loaded.");
            }
            
        }
        reader.readAsDataURL($('input:file')[0].files[0]);
        
    $('#remove').css('display','unset');
    $('#remove').css('visibility','visible');
    
    $('#remove').click((e)=>{
        e.preventDefault();
      $('#img-preview').attr('src',""); 
      $('#img-preview').css('visibility','hidden');
      $('#img-preview').css('display','none');
        $('#remove').css('display','none');
    $('#remove').css('visibility','hidden');

    });
});

});

</script>